"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, LoaderCircle, Plus, X } from "lucide-react";
import { adminRequest, type AdminBooking } from "@/lib/admin-api";
import { loadAvailability } from "@/lib/booking-api";

const statusLabel = { confirmed: "Подтверждена", completed: "Завершена", cancelled: "Отменена", no_show: "Неявка" };
export function AdminBookings() {
  const router = useRouter(); const [rows, setRows] = useState<AdminBooking[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [createOpen,setCreateOpen]=useState(false);const [services,setServices]=useState<any[]>([]);const[barbers,setBarbers]=useState<any[]>([]);const [serviceId,setServiceId]=useState("");const[barberId,setBarberId]=useState("");const[date,setDate]=useState("");const[slots,setSlots]=useState<any[]>([]);const[startsAt,setStartsAt]=useState("");const[name,setName]=useState("");const[phone,setPhone]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  const [moving,setMoving]=useState<AdminBooking|null>(null);
  async function load() { try { setRows(await adminRequest("/api/v1/admin/bookings")); } catch (e: any) { if (e.status === 401) return router.replace("/admin/login"); setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  useEffect(()=>{void Promise.all([adminRequest<any[]>('/api/v1/admin/services'),adminRequest<any[]>('/api/v1/admin/barbers')]).then(([s,b])=>{setServices(s.filter(x=>x.isActive));setBarbers(b.filter(x=>x.isActive));}).catch(()=>{});},[]);
  useEffect(()=>{if(!serviceId||!barberId||!date){setSlots([]);return;}loadAvailability([serviceId],barberId,date).then(data=>setSlots(data.slots)).catch(()=>setSlots([]));},[serviceId,barberId,date]);
  async function status(id: string, value: AdminBooking["status"]) { await adminRequest(`/api/v1/admin/bookings/${id}/status`, { method: "POST", body: JSON.stringify({ status: value }) }); await load(); }
  async function create(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");try{await adminRequest('/api/v1/admin/bookings',{method:'POST',body:JSON.stringify({serviceIds:[serviceId],barberId,startsAt,client:{name,phone}})});setCreateOpen(false);setName('');setPhone('');await load();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
  useEffect(()=>{if(!moving||!date||!barberId)return;loadAvailability(moving.services.map(s=>s.serviceId),barberId,date).then(d=>setSlots(d.slots)).catch(()=>setSlots([]));},[moving,date,barberId]);
  async function reschedule(event:React.FormEvent){event.preventDefault();if(!moving||!startsAt)return;setBusy(true);setMessage('');try{await adminRequest(`/api/v1/admin/bookings/${moving.id}/reschedule`,{method:'PUT',body:JSON.stringify({barberId,startsAt})});setMoving(null);await load();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
  return <><header className="admin-page-head"><div><span>РАСПИСАНИЕ</span><h1>Записи</h1><p>Последние визиты и актуальный статус клиентов.</p></div><button onClick={()=>setCreateOpen(true)} className="admin-primary"><Plus size={18} /> Новая запись</button></header>
    {message&&<p className="admin-notice">{message}</p>}<section className="admin-panel">{loading ? <div className="admin-state"><LoaderCircle className="spin" />Загрузка записей…</div> : error ? <div className="admin-error">{error}</div> : rows.length === 0 ? <div className="admin-empty"><CalendarDays size={30} /><strong>Записей пока нет</strong></div> : <div className="admin-table-wrap"><table><thead><tr><th>Дата</th><th>Клиент</th><th>Услуга</th><th>Мастер</th><th>Статус</th><th>Сумма</th><th></th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{new Intl.DateTimeFormat("ru-RU", { timeZone: "Asia/Tashkent", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(row.startsAt))}</strong></td><td>{row.client.name}<small>{row.client.phone}</small></td><td>{row.services.map(s => s.name).join(", ")}</td><td>{row.barber.name}</td><td><select value={row.status} onChange={e => void status(row.id, e.target.value as AdminBooking["status"])} className={`status-${row.status}`}><option value="confirmed">{statusLabel.confirmed}</option><option value="completed">{statusLabel.completed}</option><option value="cancelled">{statusLabel.cancelled}</option><option value="no_show">{statusLabel.no_show}</option></select></td><td>{new Intl.NumberFormat("ru-RU").format(row.totalPrice)} сум</td><td>{row.status==="confirmed"&&<button className="admin-secondary" onClick={()=>{setMoving(row);setBarberId(row.barber.id);setDate('');setStartsAt('');setSlots([]);}}>Перенести</button>}</td></tr>)}</tbody></table></div>}</section>
    {createOpen&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setCreateOpen(false)}><form className="admin-modal admin-manual-booking" onSubmit={create}><header><h2>Новая запись</h2><button type="button" onClick={()=>setCreateOpen(false)}><X/></button></header><label>Услуга<select required value={serviceId} onChange={e=>{setServiceId(e.target.value);setStartsAt("")}}><option value="">Выбрать услугу</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} · {s.durationMin} мин</option>)}</select></label><label>Мастер<select required value={barberId} onChange={e=>{setBarberId(e.target.value);setStartsAt("")}}><option value="">Выбрать мастера</option>{barbers.filter(b=>b.serviceIds.includes(serviceId)).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Дата<input required type="date" value={date} onChange={e=>{setDate(e.target.value);setStartsAt("")}}/></label><label>Свободное время<select required value={startsAt} onChange={e=>setStartsAt(e.target.value)}><option value="">Выбрать слот</option>{slots.map(slot=><option key={slot.startsAt} value={slot.startsAt}>{slot.time}</option>)}</select></label><label>Имя клиента<input required minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label><label>Телефон<input required type="tel" placeholder="+998 90 123 45 67" value={phone} onChange={e=>setPhone(e.target.value)}/></label>{message&&<p className="admin-error">{message}</p>}<footer className="admin-modal-actions"><button className="admin-secondary" type="button" onClick={()=>setCreateOpen(false)}>Отмена</button><button className="admin-primary" disabled={busy||!startsAt}>{busy?'Сохраняем…':'Создать запись'}</button></footer></form></div>}
    {moving&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setMoving(null)}><form className="admin-modal admin-manual-booking" onSubmit={reschedule}><header><h2>Перенести запись</h2><button type="button" onClick={()=>setMoving(null)}><X/></button></header><p>{moving.client.name} · {moving.services.map(s=>s.name).join(', ')}</p><label>Мастер<select required value={barberId} onChange={e=>{setBarberId(e.target.value);setStartsAt('')}}>{barbers.filter(b=>moving.services.every(s=>b.serviceIds.includes(s.serviceId))).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Новая дата<input required type="date" value={date} onChange={e=>{setDate(e.target.value);setStartsAt('')}}/></label><label>Свободное время<select required value={startsAt} onChange={e=>setStartsAt(e.target.value)}><option value="">Выбрать слот</option>{slots.map(slot=><option key={slot.startsAt} value={slot.startsAt}>{slot.time}</option>)}</select></label>{message&&<p className="admin-error">{message}</p>}<footer className="admin-modal-actions"><button type="button" className="admin-secondary" onClick={()=>setMoving(null)}>Отмена</button><button className="admin-primary" disabled={busy||!startsAt}>{busy?'Сохраняем…':'Сохранить время'}</button></footer></form></div>}
  </>;
}
