"use client";
import { Fragment, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Check, LoaderCircle, Plus, Save, Upload, X } from "lucide-react";
import { adminRequest } from "@/lib/admin-api";

type ServiceRow = { id: string; slug: string; name: string; description: string | null; durationMin: number; price: number; isActive: boolean; sortOrder: number };
type BarberRow = { id: string; slug: string; name: string; bio: string | null; photoUrl: string | null; experienceYears: number; isActive: boolean; sortOrder: number; serviceIds: string[] };
const weekdays = ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"];
function useAdminLoad<T>(path: string) { const router = useRouter(); const [data,setData]=useState<T[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); async function load(){try{setData(await adminRequest<T[]>(path));}catch(e:any){if(e.status===401)router.replace('/admin/login');else setError(e.message);}finally{setLoading(false);}} useEffect(()=>{void load();},[path]); return {data,setData,loading,error,load}; }

export function AdminServices(){
  const {data:rows,loading,error,load}=useAdminLoad<ServiceRow>("/api/v1/admin/services"); const [editing,setEditing]=useState<ServiceRow|null>(null);const [message,setMessage]=useState("");
  function blank():ServiceRow{return{id:"",slug:"",name:"",description:"",durationMin:45,price:0,isActive:true,sortOrder:rows.length};}
  async function save(){if(!editing)return;try{const body={...editing,price:Number(editing.price),durationMin:Number(editing.durationMin),sortOrder:Number(editing.sortOrder)};await adminRequest(`/api/v1/admin/services${editing.id?`/${editing.id}`:""}`,{method:editing.id?"PUT":"POST",body:JSON.stringify(body)});setEditing(null);setMessage("Услуга сохранена");await load();}catch(e:any){setMessage(e.message);}}
  return <><Head kicker="КАТАЛОГ" title="Услуги" description="Цены и длительность услуг, которые видят клиенты." add={()=>setEditing(blank())}/>{message&&<p className="admin-notice">{message}</p>}<div className="admin-cards">{loading?<State/>:error?<p className="admin-error">{error}</p>:rows.map(row=><article className="admin-card" key={row.id}><div><span className="admin-kicker">{row.durationMin} МИН · {row.isActive?"АКТИВНА":"СКРЫТА"}</span><h2>{row.name}</h2><p>{row.description}</p><strong>{new Intl.NumberFormat("ru-RU").format(row.price)} сум</strong></div><button className="admin-secondary" onClick={()=>setEditing({...row})}>Изменить</button></article>)}</div>{editing&&<Modal title={editing.id?"Изменить услугу":"Новая услуга"} close={()=>setEditing(null)}><div className="admin-form-grid"><Field label="Название" value={editing.name} change={name=>setEditing({...editing,name})}/><Field label="Slug (латиницей)" value={editing.slug} change={slug=>setEditing({...editing,slug})}/><Field label="Длительность, минут" type="number" value={editing.durationMin} change={durationMin=>setEditing({...editing,durationMin:Number(durationMin)})}/><Field label="Цена, сум" type="number" value={editing.price} change={price=>setEditing({...editing,price:Number(price)})}/><Field label="Описание" value={editing.description??""} change={description=>setEditing({...editing,description})}/><label className="admin-check"><input type="checkbox" checked={editing.isActive} onChange={e=>setEditing({...editing,isActive:e.target.checked})}/> Показывать клиентам</label></div><ModalActions save={save} close={()=>setEditing(null)}/></Modal>}</>;
}

export function AdminBarbers(){
  const {data:rows,loading,error,load}=useAdminLoad<BarberRow>("/api/v1/admin/barbers");const [services,setServices]=useState<ServiceRow[]>([]);const [editing,setEditing]=useState<BarberRow|null>(null);const [message,setMessage]=useState("");const [portfolio,setPortfolio]=useState<any[]>([]);const [portfolioUrl,setPortfolioUrl]=useState("");
  useEffect(()=>{adminRequest<ServiceRow[]>("/api/v1/admin/services").then(setServices).catch(()=>{});},[]);
  useEffect(()=>{if(editing?.id)adminRequest<any[]>(`/api/v1/admin/barbers/${editing.id}/portfolio`).then(setPortfolio).catch(()=>setPortfolio([]));else setPortfolio([]);},[editing?.id]);
  function blank():BarberRow{return{id:"",slug:"",name:"",bio:"",photoUrl:"",experienceYears:0,isActive:true,sortOrder:rows.length,serviceIds:[]};}
  async function save(){if(!editing)return;try{await adminRequest(`/api/v1/admin/barbers${editing.id?`/${editing.id}`:""}`,{method:editing.id?"PUT":"POST",body:JSON.stringify({...editing,experienceYears:Number(editing.experienceYears)})});setEditing(null);setMessage("Профиль мастера сохранён");await load();}catch(e:any){setMessage(e.message);}}
  async function upload(file:File){if(!editing?.id)return;const form=new FormData();form.append("file",file);try{const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??(process.env.NODE_ENV==="production"?"":"http://127.0.0.1:3001")}/api/v1/admin/barbers/${editing.id}/photo`,{method:"POST",credentials:"include",body:form});const body=await r.json();if(!r.ok)throw new Error(body.error?.message??"Ошибка загрузки");setEditing({...editing,photoUrl:body.data.photoUrl});}catch(e:any){setMessage(e.message);}}
  async function addPortfolio(){if(!editing?.id||!portfolioUrl.trim())return;try{const item=await adminRequest<any>(`/api/v1/admin/barbers/${editing.id}/portfolio`,{method:"POST",body:JSON.stringify({imageUrl:portfolioUrl.trim(),sortOrder:portfolio.length})});setPortfolio([...portfolio,item]);setPortfolioUrl("");}catch(e:any){setMessage(e.message);}}
  return <><Head kicker="КОМАНДА" title="Мастера" description="Профили, фотографии, услуги и расписание команды." add={()=>setEditing(blank())}/>{message&&<p className="admin-notice">{message}</p>}<div className="admin-cards">{loading?<State/>:error?<p className="admin-error">{error}</p>:rows.map(row=><article className="admin-card admin-barber-card" key={row.id}>{row.photoUrl?<img src={row.photoUrl} alt=""/>:<div className="admin-photo-placeholder">{row.name.slice(0,1)}</div>}<div><span className="admin-kicker">{row.experienceYears} ЛЕТ · {row.isActive?"АКТИВЕН":"СКРЫТ"}</span><h2>{row.name}</h2><p>{row.bio}</p><LinkButton href={`/admin/schedule?barber=${row.id}`}>Расписание</LinkButton></div><button className="admin-secondary" onClick={()=>setEditing({...row})}>Изменить</button></article>)}</div>{editing&&<Modal title={editing.id?"Профиль мастера":"Новый мастер"} close={()=>setEditing(null)}><div className="admin-form-grid"><Field label="Имя" value={editing.name} change={name=>setEditing({...editing,name})}/><Field label="Slug" value={editing.slug} change={slug=>setEditing({...editing,slug})}/><Field label="Стаж, лет" type="number" value={editing.experienceYears} change={experienceYears=>setEditing({...editing,experienceYears:Number(experienceYears)})}/><Field label="Фото (URL)" value={editing.photoUrl??""} change={photoUrl=>setEditing({...editing,photoUrl})}/><Field label="О мастере" value={editing.bio??""} change={bio=>setEditing({...editing,bio})}/>{editing.id&&<label className="admin-upload"><Upload size={16}/>Загрузить фото<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/></label>}<div className="admin-service-checks"><span>Услуги мастера</span>{services.map(s=><label key={s.id}><input type="checkbox" checked={editing.serviceIds.includes(s.id)} onChange={e=>setEditing({...editing,serviceIds:e.target.checked?[...editing.serviceIds,s.id]:editing.serviceIds.filter(x=>x!==s.id)})}/>{s.name}</label>)}</div><label className="admin-check"><input type="checkbox" checked={editing.isActive} onChange={e=>setEditing({...editing,isActive:e.target.checked})}/> Показывать на сайте</label></div>{editing.id&&<div className="admin-portfolio"><strong>Портфолио мастера</strong><div>{portfolio.map(item=><figure key={item.id}><img src={item.imageUrl} alt="Работа мастера"/><button onClick={async()=>{await adminRequest(`/api/v1/admin/portfolio/${item.id}`,{method:"DELETE"});setPortfolio(p=>p.filter(x=>x.id!==item.id));}}><X size={14}/></button></figure>)}</div><input value={portfolioUrl} onChange={e=>setPortfolioUrl(e.target.value)} placeholder="URL фотографии работы"/><button className="admin-secondary" onClick={()=>void addPortfolio()}><Plus size={15}/> Добавить работу</button></div>}<ModalActions save={save} close={()=>setEditing(null)}/></Modal>}</>;
}

export function AdminSchedule(){const router=useRouter();const {data:barbers}=useAdminLoad<BarberRow>("/api/v1/admin/barbers");const[barberId,setBarberId]=useState("");const[hours,setHours]=useState<any[]>([]);const[breaks,setBreaks]=useState<any[]>([]);const[timeOff,setTimeOff]=useState<any[]>([]);const[message,setMessage]=useState("");
 useEffect(()=>{const id=new URLSearchParams(location.search).get("barber");if(id)setBarberId(id);},[]);
 useEffect(()=>{if(!barberId)return;adminRequest<any>(`/api/v1/admin/barbers/${barberId}/schedule`).then(d=>{setHours(d.hours);setBreaks(d.breaks);setTimeOff(d.timeOff);}).catch(e=>{if(e.status===401)router.replace('/admin/login');else setMessage(e.message);});},[barberId]);
 async function save(){try{await adminRequest(`/api/v1/admin/barbers/${barberId}/schedule`,{method:"PUT",body:JSON.stringify({hours,breaks})});setMessage("Расписание сохранено");}catch(e:any){setMessage(e.message);}}
 async function addOff(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);try{await adminRequest('/api/v1/admin/time-off',{method:'POST',body:JSON.stringify({barberId,startsAt:new Date(String(fd.get('start'))).toISOString(),endsAt:new Date(String(fd.get('end'))).toISOString(),type:String(fd.get('type')),note:String(fd.get('note')||'')})});const d=await adminRequest<any>(`/api/v1/admin/barbers/${barberId}/schedule`);setTimeOff(d.timeOff);event.currentTarget.reset();}catch(e:any){setMessage(e.message);}}
 return <><Head kicker="РАСПИСАНИЕ" title="График работы" description="Рабочие часы, обеды и исключения для мастеров."/><div className="admin-toolbar"><label>Мастер<select value={barberId} onChange={e=>setBarberId(e.target.value)}><option value="">Выбрать мастера</option>{barbers.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div>{barberId&&<><section className="admin-panel admin-schedule">{hours.map((row,i)=><div className="schedule-row" key={row.weekday}><strong>{weekdays[row.weekday]}</strong><input type="checkbox" aria-label="Выходной" checked={row.off} onChange={e=>setHours(h=>h.map((x,n)=>n===i?{...x,off:e.target.checked}:x))}/><input type="time" disabled={row.off} value={row.start} onChange={e=>setHours(h=>h.map((x,n)=>n===i?{...x,start:e.target.value}:x))}/><span>—</span><input type="time" disabled={row.off} value={row.end} onChange={e=>setHours(h=>h.map((x,n)=>n===i?{...x,end:e.target.value}:x))}/><small>{row.off?"Выходной":"Работает"}</small></div>)}</section><h2 className="admin-subtitle">Обеденные перерывы</h2><section className="admin-panel admin-schedule">{breaks.map((row,i)=><div className="schedule-row" key={i}><select value={row.weekday} onChange={e=>setBreaks(b=>b.map((x,n)=>n===i?{...x,weekday:Number(e.target.value)}:x))}>{weekdays.map((d,n)=><option value={n} key={n}>{d}</option>)}</select><input type="time" value={row.start} onChange={e=>setBreaks(b=>b.map((x,n)=>n===i?{...x,start:e.target.value}:x))}/><span>—</span><input type="time" value={row.end} onChange={e=>setBreaks(b=>b.map((x,n)=>n===i?{...x,end:e.target.value}:x))}/><button onClick={()=>setBreaks(b=>b.filter((_,n)=>n!==i))}><X size={16}/></button></div>)}<button className="admin-secondary" onClick={()=>setBreaks(b=>[...b,{weekday:1,start:"14:00",end:"15:00"}])}><Plus size={16}/> Добавить обед</button></section><button className="admin-primary admin-save" onClick={()=>void save()}><Save size={16}/> Сохранить график</button><h2 className="admin-subtitle">Выходные и исключения</h2><form className="admin-panel admin-timeoff-form" onSubmit={addOff}><label>С<input name="start" type="datetime-local" required/></label><label>По<input name="end" type="datetime-local" required/></label><select name="type"><option value="day_off">Выходной</option><option value="vacation">Отпуск</option><option value="sick_leave">Больничный</option><option value="other">Другое</option></select><input name="note" placeholder="Комментарий"/><button className="admin-primary">Добавить</button></form><div className="admin-cards">{timeOff.map(item=><article className="admin-card" key={item.id}><div><strong>{new Date(item.startsAt).toLocaleString("ru-RU")}</strong><p>{item.note||item.type}</p></div><button className="admin-secondary" onClick={async()=>{await adminRequest(`/api/v1/admin/time-off/${item.id}`,{method:'DELETE'});setTimeOff(v=>v.filter(x=>x.id!==item.id));}}>Удалить</button></article>)}</div></>}{message&&<p className="admin-notice">{message}</p>}</>;
}

export function AdminSettings(){const[settings,setSettings]=useState<any>(null);const[message,setMessage]=useState("");const router=useRouter();useEffect(()=>{adminRequest<any>('/api/v1/admin/settings').then(setSettings).catch(e=>{if(e.status===401)router.replace('/admin/login');else setMessage(e.message);});},[]);async function save(){try{await adminRequest('/api/v1/admin/settings',{method:'PUT',body:JSON.stringify({...settings,cancel_cutoff_min:+settings.cancel_cutoff_min,slot_step_min:+settings.slot_step_min,booking_horizon_days:+settings.booking_horizon_days,min_notice_min:+settings.min_notice_min,reminder_day_minutes:+settings.reminder_day_minutes,reminder_short_minutes:+settings.reminder_short_minutes,review_delay_min:+settings.review_delay_min,review_public_min_rating:+settings.review_public_min_rating})});setMessage('Настройки сохранены');}catch(e:any){setMessage(e.message);}}return <><Head kicker="ПРАВИЛА" title="Настройки" description="Часовой пояс, запись, напоминания и отзывы."/>{settings&&<section className="admin-panel admin-settings-grid">{[["timezone","Часовой пояс","text"],["cancel_cutoff_min","До визита нельзя отменить (минуты)","number"],["slot_step_min","Шаг времени записи (минуты)","number"],["booking_horizon_days","Запись вперёд (дней)","number"],["min_notice_min","Минимум до визита (минуты)","number"],["reminder_day_minutes","Напоминание за (минуты)","number"],["reminder_short_minutes","Короткое напоминание за (минуты)","number"],["review_delay_min","Запрос отзыва после визита (минуты)","number"],["review_public_min_rating","Минимальная оценка для публикации", "number"]].map(([key,label,type])=><label key={key}>{label}<input type={type} value={settings[key]??""} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}<button className="admin-primary" onClick={()=>void save()}><Save size={16}/> Сохранить</button></section>}{message&&<p className="admin-notice">{message}</p>}</>}

export function AdminReviews(){const{data:rows,loading,error,load}=useAdminLoad<any>('/api/v1/admin/reviews');async function visible(id:string,isPublic:boolean){await adminRequest(`/api/v1/admin/reviews/${id}`,{method:'PUT',body:JSON.stringify({isPublic})});await load();}return <><Head kicker="ОТКЛИКИ" title="Отзывы" description="Проверяйте отзывы гостей и выбирайте, какие показывать на сайте."/>{loading?<State/>:error?<p className="admin-error">{error}</p>:<div className="admin-cards">{rows.map(row=><article className="admin-card" key={row.id}><div><span className="admin-kicker">{"★".repeat(row.rating)} · {row.isPublic?"ОПУБЛИКОВАН":"СКРЫТ"}</span><h2>{row.client.name}</h2><p>{row.comment||"Без текста"}</p><small>{row.barber.name} · {new Date(row.booking.startsAt).toLocaleDateString('ru-RU')}</small></div><button className="admin-secondary" onClick={()=>void visible(row.id,!row.isPublic)}>{row.isPublic?"Скрыть":"Опубликовать"}</button></article>)}</div>}</>}

type AnalyticsData={period:{from:string;to:string};summary:{revenue:number;completed:number;bookings:number;cancelled:number;noShow:number;uniqueClients:number;returningClients:number;returningRate:number};popularServices:Array<{serviceId:string;name:string;count:number;revenue:number}>;barberLoad:Array<{id:string;name:string;availableMinutes:number;bookedMinutes:number;utilization:number}>;heatmap:number[][]};
function tashkentToday(){return new Date(Date.now()+5*3600000).toISOString().slice(0,10)}
function shiftDate(value:string,days:number){const d=new Date(`${value}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
const weekdaysShort=["Вс","Пн","Вт","Ср","Чт","Пт","Сб"];
export function AdminAnalytics(){const router=useRouter();const today=tashkentToday();const[from,setFrom]=useState(shiftDate(today,-29));const[to,setTo]=useState(today);const[data,setData]=useState<AnalyticsData|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{setData(await adminRequest<AnalyticsData>(`/api/v1/admin/analytics?from=${from}&to=${to}`));}catch(e:any){if(e.status===401)router.replace('/admin/login');else setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[from,to]);
 const summary=data?.summary;const maxService=Math.max(1,...(data?.popularServices.map(x=>x.count)??[]));const maxHeat=Math.max(1,...(data?.heatmap.flat()??[]));
 function setPreset(days:number){setTo(today);setFrom(shiftDate(today,-(days-1)));}
 return <><header className="admin-page-head"><div><span>ПОКАЗАТЕЛИ</span><h1>Аналитика</h1><p>Работа барбершопа за выбранный период.</p></div></header><section className="admin-analytics-toolbar"><div className="admin-period-presets">{[7,30,90].map(days=><button key={days} className={from===shiftDate(today,-(days-1))&&to===today?"active":""} onClick={()=>setPreset(days)}>{days} дней</button>)}</div><label>С<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>По<input type="date" value={to} min={from} max={today} onChange={e=>setTo(e.target.value)}/></label></section>
 {error&&<p className="admin-error">{error}</p>}{loading&&!data?<div className="admin-state"><LoaderCircle className="spin"/>Считаем показатели…</div>:summary&&<><section className="admin-metric-grid"><Metric title="Выручка" value={`${new Intl.NumberFormat("ru-RU").format(summary.revenue)} сум`} note="Завершённые записи"/><Metric title="Записи" value={summary.bookings} note={`${summary.completed} завершено`}/><Metric title="Отмены" value={summary.cancelled} note={`${summary.noShow} неявок`}/><Metric title="Возвращаемость" value={`${summary.returningRate}%`} note={`${summary.returningClients} из ${summary.uniqueClients} клиентов вернулись`}/></section>
 <section className="admin-analytics-grid"><article className="admin-panel admin-chart-panel"><header><div><span className="admin-kicker">СПРОС</span><h2>Популярные услуги</h2></div><small>Завершённые и активные записи</small></header>{data!.popularServices.length?data!.popularServices.map(item=><div className="analytics-bar-row" key={item.serviceId}><span>{item.name}</span><div><i style={{width:`${Math.max(4,item.count/maxService*100)}%`}}/></div><strong>{item.count}</strong></div>):<p className="admin-muted">За период записей нет.</p>}</article>
 <article className="admin-panel admin-chart-panel"><header><div><span className="admin-kicker">ЗАГРУЗКА</span><h2>Мастера</h2></div><small>Занятое время от расписания</small></header>{data!.barberLoad.map(item=><div className="analytics-bar-row" key={item.id}><span>{item.name}</span><div><i style={{width:`${item.utilization}%`}}/></div><strong>{item.utilization}%</strong></div>)}</article></section>
 <section className="admin-panel admin-heatmap"><header><div><span className="admin-kicker">РАСПРЕДЕЛЕНИЕ СПРОСА</span><h2>День недели × час</h2></div><small>Записи по местному времени Ташкента</small></header><div className="heatmap-scroll"><div className="heatmap-grid"><span/>{Array.from({length:24},(_,hour)=><small key={hour}>{String(hour).padStart(2,'0')}</small>)}{weekdaysShort.map((day,weekday)=><Fragment key={day}><strong>{day}</strong>{data!.heatmap[weekday].map((count,hour)=><span key={hour} title={`${day}, ${hour}:00 — ${count} ${count===1?'запись':'записей'}`} style={{opacity:count?0.2+0.8*count/maxHeat:0.08}}>{count||''}</span>)}</Fragment>)}</div></div><footer><span>Меньше</span><i/><i/><i/><i/><span>Больше</span></footer></section></>}
 </>;
}
function Metric({title,value,note}:{title:string;value:string|number;note:string}){return <article className="admin-panel admin-metric"><span>{title}</span><strong>{value}</strong><small>{note}</small></article>}

function Head({kicker,title,description,add}:{kicker:string;title:string;description:string;add?:()=>void}){return <header className="admin-page-head"><div><span>{kicker}</span><h1>{title}</h1><p>{description}</p></div>{add&&<button className="admin-primary" onClick={add}><Plus size={18}/>Добавить</button>}</header>}
function State(){return <div className="admin-state"><LoaderCircle className="spin"/>Загрузка…</div>}
function Field({label,value,change,type="text"}:{label:string;value:string|number;change:(v:string)=>void;type?:string}){return <label>{label}<input type={type} value={value} onChange={e=>change(e.target.value)} /></label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="admin-modal"><header><h2>{title}</h2><button onClick={close}><X/></button></header>{children}</section></div>}
function ModalActions({save,close}:{save:()=>void;close:()=>void}){return <footer className="admin-modal-actions"><button className="admin-secondary" onClick={close}>Отмена</button><button className="admin-primary" onClick={()=>void save()}><Check size={16}/>Сохранить</button></footer>}
function LinkButton({href,children}:{href:string;children:React.ReactNode}){return <a className="admin-secondary admin-link-button" href={href}>{children}</a>}
